# This is a basic workflow to help you get started with Actions

name: Continuous integration - Staging Environment

# Controls when the workflow will run
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd hml && mvn clean package
      # Runs a set of commands using the runners shell
      - name: Deploy to staging environment
        run: sh deploy.sh -d
